# All base configuration options for Boundless Economy.


# Controls if certain messages are displayed in the console.
# true - Messages WILL be displayed.
# false - Messages WILL NOT be displayed.
show-debug: false
show-stack-trace: false

# All configuration options relating to commands and command functions.
# Some messages have the supported ability of special string tags fill in specific information
# relating to the command when it is run.
# To see a more comprehensive guide on what each tag does, or to see a list of which command messages support
# which tags, visit the GitHub Wiki page on commands for more information.
Commands:
    Balance:
        message: "&f---&6Your Wallet&f---"
        message-enable: true
        show-hidden-currency: false
    BalanceOther:
        message: "&f---&6%PLAYER%'s Wallet&f---"
        message-enable: true
    Pay:
        sender-message: "&f%VALUE% %CURRENCY%&r transferred to %TARGET%."
        sender-message-enable: true
        target-message: "&f%VALUE% %CURRENCY%&r received from %SENDER%."
        target-message-enable: true
        timer: 5
        timer-message: "Please wait &6%TIME%&r before using that command again."
        timer-enable: true
    Economy:
        Give:
            sender-message: "%VALUE% %CURRENCY%&r has been given to %TARGET%."
            sender-message-enable: true
            target-message: "%SENDER% has given you %VALUE% %CURRENCY%&r."
            target-message-enable: true
        Subtract:
            sender-message: "%VALUE% %CURRENCY%&r has been taken from %TARGET%."
            sender-message-enable: true
            target-message: "%SENDER% has taken %VALUE% %CURRENCY%&r from you."
            target-message-enable: true
        Set:
            sender-message: "%TARGET%'s balance has been set to %VALUE% %CURRENCY%&r.X"
            sender-message-enable: true
            target-message: "%SENDER% has set your %CURRENCY%&r balance to %VALUE%."
            target-message-enable: true